### ISSUE TITLE
Idanode submission

### ISSUE THREAD

**Issue by cryptojoystick** [scryptachain/scrypta-idanode-network#1]
INDIRIZZO_IP: 64.227.122.216 
PUBKEY_IDANODE:0354a543b2605fdac5225482b0124bd4a1bd7b5a5b9f804be9c091fe987e6493ac

**Comment by turinglabsorg** [comment]
Assigned domain is `https://idanodejs07.scryptachain.org` please run following commands inside `scrypta-idanodejs` folder:

```
chmod 777 secure.sh
./secure.sh idanodejs07.scryptachain.org
```

Last command will produce the instructions to secure the idanode with `certbot`.

**Comment by turinglabsorg** [comment]
Correctly added with commit https://github.com/scryptachain/scrypta-idanode-network/commit/eccea8a95c8445261e830209bf0c68fb102e4dc9
