### ISSUE TITLE
Nuovo idanode

### ISSUE THREAD

**Issue by pf55351** [scryptachain/scrypta-idanode-network#10]
Indirizzo ip  64.227.110.67
pubkey: 036127d775cf02150bf4d18b66fbc07bdb4f949dbc35d4c26774c9378602f7a69a

ciao
F

**Comment by turinglabsorg** [comment]
Assigned domain is https://idanodejs16.scryptachain.org please run following commands inside scrypta-idanodejs folder:
```
chmod 777 secure.sh
./secure.sh idanodejs16.scryptachain.org
Last command will produce the instructions to secure the idanode with certbot.
```

**Comment by turinglabsorg** [comment]
added with commit https://github.com/scryptachain/scrypta-idanode-network/commit/379cc825a5b23af4a4711d6c70f36aa7561c6afe

**Comment by turinglabsorg** [comment]
@pf55351 Idanode is still active or can we delete it?
