### ISSUE TITLE
Idanode Submission

### ISSUE THREAD

**Issue by pciccioni** [scryptachain/scrypta-idanode-network#2]
INDIRIZZO_IP: 52.183.98.22
PUBKEY_IDANODE: 03cc2ba0339aa1968086547743d3d005b2faddfd42c6a59fbe820edf781f83a7f5

**Comment by SBridda** [comment]
INDIRIZZO_IP: 151.49.57.24
PUBKEY_IDANODE: 02065776a04416694eb3c440500718a7db504c1c42a9cd43ec036fa5c40c09bb39

**Comment by turinglabsorg** [comment]
Assigned domain is https://idanodejs08.scryptachain.org please run following commands inside scrypta-idanodejs folder:
```
chmod 777 secure.sh
./secure.sh idanodejs08.scryptachain.org
```
Last command will produce the instructions to secure the idanode with certbot.

**Comment by turinglabsorg** [comment]
Added with commit https://github.com/scryptachain/scrypta-idanode-network/commit/b9a461c9171f2fad33865424cc8a8358136ca20d
