### ISSUE TITLE
Idanode Submission

### ISSUE THREAD

**Issue by SBridda** [scryptachain/scrypta-idanode-network#3]
**INDIRIZZO_IP**: 151.49.57.24
**PUBKEY_IDANODE**: 02065776a04416694eb3c440500718a7db504c1c42a9cd43ec036fa5c40c09bb39

**Comment by turinglabsorg** [comment]
Assigned domain is https://idanodejs09.scryptachain.org please run following commands inside scrypta-idanodejs folder:
```
chmod 777 secure.sh
./secure.sh idanodejs09.scryptachain.org
```
Last command will produce the instructions to secure the idanode with certbot.

**Comment by turinglabsorg** [comment]
did you have the chance to run the idanode with SSL?

**Comment by SBridda** [comment]
Not yet.

Tomorrow I play the last chance.

Il giorno lun 15 giu 2020 alle ore 17:02 turinglabs <
notifications@github.com> ha scritto:

**Comment by SBridda** [comment]
(update)

 **INDIRIZZO_IP**: 151.49.124.165
 **PUBKEY_IDANODE**: 02065776a04416694eb3c440500718a7db504c1c42a9cd43ec036fa5c40c09bb39

**Comment by turinglabsorg** [comment]
Closing, added with commit https://github.com/scryptachain/scrypta-idanode-network/commit/ca69493c5afb607f78ca3a6f3d8fedcc774f3dcb
