### ISSUE TITLE
IdaNode Registration

### ISSUE THREAD

**Issue by cerino60** [scryptachain/scrypta-idanode-network#4]
Public IP: 40.87.100.206
PUBKEY_IDANODE: 03e2e22b142a86fc981bc704c1954720340a566bf31f50e42778877ab050db581f

**Comment by turinglabsorg** [comment]
Assigned domain is https://idanodejs10.scryptachain.org please run following commands inside scrypta-idanodejs folder:
```
chmod 777 secure.sh
./secure.sh idanodejs10.scryptachain.org
```
Last command will produce the instructions to secure the idanode with certbot.

**Comment by turinglabsorg** [comment]
Added with commit https://github.com/scryptachain/scrypta-idanode-network/commit/a6fa66459d856f715f5fc851bc73aea75a45fb79
