### ISSUE TITLE
IdaNode request

### ISSUE THREAD

**Issue by cerino60** [scryptachain/scrypta-idanode-network#5]
PUBLIC IP: 35.209.3.7
PUBKEY_IDANODE:  03e084fcfbb174c83e1b13e3bd2f8c02ae478051023176b749513d8cc56395a652

**Comment by turinglabsorg** [comment]
Assigned domain is https://idanodejs11.scryptachain.org please run following commands inside scrypta-idanodejs folder:

chmod 777 secure.sh
./secure.sh idanodejs11.scryptachain.org
Last command will produce the instructions to secure the idanode with certbot.

**Comment by cerino60** [comment]
All done

**Comment by turinglabsorg** [comment]
added with commit https://github.com/scryptachain/scrypta-idanode-network/commit/02adc38bb9ce22f10d7b5538b52c8427423f0e8e
