### ISSUE TITLE
idaNode request

### ISSUE THREAD

**Issue by archimedix** [scryptachain/scrypta-idanode-network#6]
PUBLIC IP: 37.187.121.2
PUBKEY_IDANODE: 02334a912e1f10311191721951aa053e3b1ff2444e6e97fbdfb4ca6e051dd6a189

**Comment by turinglabsorg** [comment]
Assigned domain is https://idanodejs12.scryptachain.org please run following commands inside scrypta-idanodejs folder:

chmod 777 secure.sh
./secure.sh idanodejs12.scryptachain.org
Last command will produce the instructions to secure the idanode with certbot.

**Comment by turinglabsorg** [comment]
IdaNode is connected and added to the pool, however it's not syncing, please check why it's not working properly or just try to reboot the service with `pm2 restart npm`.

You can even follow these instructions to speed-up the syincing process:
```
pm2 stop npm
reboot
```
Wait until the machine is already available, then:
```
chmod 777 bootstrap.sh
./bootstrap.sh
```

![image](https://user-images.githubusercontent.com/14848252/84030079-b62e5d80-a993-11ea-84b6-607edd9183af.png)

**Comment by archimedix** [comment]
should be ok now

**Comment by archimedix** [comment]
Looking logs i found an error:
```
Database not connected, starting process now.
Waiting 5 seconds, then try again.
(node:18730) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'db' of undefined
    at /home/scrypta-idanodejs/dist/routes/Wallet.js:25:39
    at Generator.next (<anonymous>)
    at /home/scrypta-idanodejs/dist/routes/Wallet.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/scrypta-idanodejs/dist/routes/Wallet.js:4:12)
    at /home/scrypta-idanodejs/dist/routes/Wallet.js:24:24
    at /home/scrypta-idanodejs/node_modules/mongodb/lib/utils.js:722:9
    at /home/scrypta-idanodejs/node_modules/mongodb/lib/mongo_client.js:219:23
    at connectCallback (/home/scrypta-idanodejs/node_modules/mongodb/lib/operations/connect.js:356:5)
    at /home/scrypta-idanodejs/node_modules/mongodb/lib/operations/connect.js:589:14
(node:18730) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18730) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
After this error the sync start for some minute, after log are only:
```
...
LYRA wallet successfully connected.
Database connected successfully.
LYRA wallet successfully connected.
Database connected successfully.
LYRA wallet successfully connected.
...
```
and sync seem to stop.

**Comment by turinglabsorg** [comment]
Are you sure that the server have enough CPU and RAM?

The error is not linked with the sync, it seems that something crashes, can you find the log of the last scanned block before the crash?

**Comment by archimedix** [comment]
I try to solve problems, but my machine is used with other services, and it is a ubuntu 18.
Now i just start a new VPS exclusive for idanode. In the future i work for a dockerized version.
New VPS seem full synch now.
NEW_IP: 51.210.100.143
PUBKEY_IDANODE: 0337e61f808d0e6ded1bec2c21054e7e2ff1ad0f04eb213d90450b6fc368eadb60

**Comment by turinglabsorg** [comment]
ok updated, please proceed with `secure.sh` script.

**Comment by archimedix** [comment]
all done!

**Comment by archimedix** [comment]
I'm not see anymore my node in https://watchtower.scryptachain.org.

**Comment by turinglabsorg** [comment]
IdaNode has been offline for 14000 blocks or something like that, we thought you just leaving the pool. I'll insert it again in the peers file.

**Comment by turinglabsorg** [comment]
Relisted with commit https://github.com/scryptachain/scrypta-idanode-network/commit/09397fcae2d257dd53900483c55283dc27305c5c
