### ISSUE TITLE
IdaNode submission

### ISSUE THREAD

**Issue by pciccioni** [scryptachain/scrypta-idanode-network#7]
PUBLIC IP:  40.87.96.143
PUBKEY_IDANODE: 03775cc983eb0c009c683dcadbdeab059704f5db137c59fc70aa985fc365fcf684

**Comment by turinglabsorg** [comment]
Assigned domain is https://idanodejs13.scryptachain.org please run following commands inside scrypta-idanodejs folder:
```
chmod 777 secure.sh
./secure.sh idanodejs13.scryptachain.org
```
Last command will produce the instructions to secure the idanode with certbot.

**Comment by pciccioni** [comment]
All done.

**Comment by turinglabsorg** [comment]
added with commit https://github.com/scryptachain/scrypta-idanode-network/commit/02adc38bb9ce22f10d7b5538b52c8427423f0e8e
