### ISSUE TITLE
IdaNode registration

### ISSUE THREAD

**Issue by cerino60** [scryptachain/scrypta-idanode-network#8]
PUBLIC IP: 34.86.199.114
PUBKEY_IDANODE: 03af1dbe5f27b92fd5a1b648efee48004107ae650094dae6bcb16dd790c70885c5

**Comment by turinglabsorg** [comment]
Assigned domain is https://idanodejs14.scryptachain.org please run following commands inside scrypta-idanodejs folder:
```
chmod 777 secure.sh
./secure.sh idanodejs14.scryptachain.org
```
Last command will produce the instructions to secure the idanode with certbot.

**Comment by cerino60** [comment]
All done

**Comment by turinglabsorg** [comment]
Added with commit https://github.com/scryptachain/scrypta-idanode-network/commit/02adc38bb9ce22f10d7b5538b52c8427423f0e8e
