### ISSUE TITLE
IDANODE Request

### ISSUE THREAD

**Issue by pciccioni** [scryptachain/scrypta-idanode-network#9]
PUBLIC IP: 20.185.34.133
PUBKEY_IDANODE: 023302b012f31b8330d0c2e9338ab249950da404bdbaf9c89e235eb80c959c400c

**Comment by turinglabsorg** [comment]
Assigned domain is https://idanodejs15.scryptachain.org please run following commands inside scrypta-idanodejs folder:
```
chmod 777 secure.sh
./secure.sh idanodejs15.scryptachain.org
```
Last command will produce the instructions to secure the idanode with certbot.

**Comment by pciccioni** [comment]
All done

**Comment by turinglabsorg** [comment]
IdANode can't be reached, please check it.

**Comment by pciccioni** [comment]
Now it's ok

**Comment by turinglabsorg** [comment]
Added with commit https://github.com/scryptachain/scrypta-idanode-network/commit/ed58060169018cbc1ea4d1916e2ba159e6898f20
